name: firebase_performance_example
description: Demonstrates how to use the firebase_performance plugin.
author: Flutter Team <flutter-dev@googlegroups.com>

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  http:
    git:
      url: https://github.com/dart-lang/http
      ref: d5c678cd63c3e9c1d779a09acfa95b7e3af84665
  flutter:
    sdk: flutter
  firebase_performance:
    path: ../
  firebase_core:
    path: ../../firebase_core/firebase_core

dependency_overrides:
  firebase_core:
    path: ../../firebase_core/firebase_core
  firebase_core_platform_interface:
    path: ../../firebase_core/firebase_core_platform_interface

dev_dependencies:
  pedantic: ^1.8.0
  e2e: ^0.6.1
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter

flutter:
  uses-material-design: true
