name: firebase_core_example
description: Demonstrates how to use the firebase_core plugin.

dependencies:
  flutter:
    sdk: flutter
  firebase_core:
    path: ../

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  drive: 0.0.1-6.0.pre

flutter:
  uses-material-design: true

environment:
  sdk: '>=2.12.0-29.10.beta <3.0.0'
