name: cloud_firestore_platform_interface
description: A common platform interface for the cloud_firestore plugin.
version: 2.2.1-nullsafety
homepage: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/cloud_firestore/cloud_firestore_platform_interface

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.3.0-nullsafety.6
  collection: ^1.14.3
  firebase_core: ^0.5.3-nullsafety
  plugin_platform_interface: ^1.1.0-nullsafety.1
dev_dependencies:
  firebase_core_platform_interface: "^2.1.0"
  pedantic: ^1.8.0
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0-nullsafety.0
environment:
  sdk: '>=2.12.0-29.10.beta <3.0.0'
  flutter: ">=1.9.1+hotfix.5 <2.0.0"
