name: firebase_core
description: Flutter plugin for Firebase Core, enabling connecting to multiple
  Firebase apps.
homepage: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_core/firebase_core
version: 0.5.3-nullsafety

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.firebase.core
        pluginClass: FlutterFirebaseCorePlugin
      ios:
        pluginClass: FLTFirebaseCorePlugin
      macos:
        pluginClass: FLTFirebaseCorePlugin
      web:
        default_package: firebase_core_web

dependencies:
  firebase_core_platform_interface: ^2.1.0-nullsafety
  flutter:
    sdk: flutter
  quiver: ^3.0.0-nullsafety.2
  meta: ^1.3.0-nullsafety.6
  firebase_core_web: ^0.2.1-nullsafety+1
dev_dependencies:
  pedantic: ^1.8.0
  plugin_platform_interface: ^1.1.0-nullsafety.1
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0-nullsafety.0
environment:
  sdk: '>=2.12.0-29.10.beta <3.0.0'
  flutter: ">=1.12.13+hotfix.5 <2.0.0"
