name: firebase_auth_example
description: Demonstrates how to use the firebase_auth plugin.
author: Flutter Team <flutter-dev@googlegroups.com>

dependencies:
  firebase_auth:
    path: ../
  firebase_core:
    path: ../../../firebase_core/firebase_core
  firebase_dynamic_links:
    path: ../../../firebase_dynamic_links
  flutter:
    sdk: flutter
  flutter_signin_button: ^1.0.0
  google_sign_in: ^4.5.1
  http: any
  uuid: ^2.0.2

dependency_overrides:
  firebase_core:
    path: ../../../firebase_core/firebase_core
  firebase_dynamic_links:
    path: ../../../firebase_dynamic_links

dev_dependencies:
  drive: 0.0.1-6.0.pre
  e2e: ^0.6.1
  flutter_driver:
    sdk: flutter
  pedantic: ^1.8.0
  test: any

flutter:
  uses-material-design: true

environment:
  sdk: ">=2.1.0 <3.0.0"
